CREATE TABLE [dbo].[Attachments](
	[Id] [bigint] NOT NULL,
	[Name] [nvarchar](250) NULL,
	[Size] [bigint] NULL,
	[Url] [nvarchar](2048) NULL,
 CONSTRAINT [PK_Attachments] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO