CREATE TABLE [dbo].[UserRooms](
	[Id] [bigint] NOT NULL IDENTITY,
	[UserId] [bigint] NULL,
	[RoomId] [bigint] NULL,
 [UpdDate] DATETIME NULL, 
    CONSTRAINT [PK_UserRooms] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO